name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Обов'язково змініть це тут!
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool libtool-bin m4 pkg-config libffi-dev
          pip install --user --upgrade pip
          pip install --user "cython<3.0.0" "setuptools<70.0.0" buildozer
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH
          
      - name: Install Buildozer and Cython
        run: |
          pip install --user --upgrade pip
          pip install --user "cython<3.0.0" "setuptools<70.0.0" buildozer
          # Цей рядок "лікує" помилку, додаючи шлях до Cython у середовище GitHub
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # Додаткова перевірка шляху безпосередньо перед запуском
          export PATH=$PATH:$(python3 -m site --user-base)/bin
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          buildozer -v android debug
          
      - name: Build with Buildozer
        run: |
          # Приймаємо ліцензії через прямий шлях до sdkmanager
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          
          # Очищення та збірка
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
          
